services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    environment:
      - WATCHFILES_FORCE_POLLING=true # ホットリロードのための設定
    depends_on:
      - postgres
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  chromadb:
    image: chromadb/chroma
    ports:
      - "8080:8000"
    volumes:
      - ./chromadb:/path/to/data
    environment:
      - CHROMADB_USER=user
      - CHROMADB_PASSWORD=password