"""Add default timestamps to chat_rooms

Revision ID: 3eeb9c1903da
Revises: 24b602a2b395
Create Date: 2024-11-02 06:35:19.519186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = "3eeb9c1903da"
down_revision: Union[str, None] = "24b602a2b395"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_rooms",
        "created_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
    )
    op.alter_column(
        "chat_rooms",
        "updated_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
        onupdate=func.now(),
    )
    op.alter_column(
        "chat_histories",
        "created_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
    )
    op.alter_column(
        "chat_histories",
        "updated_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
        onupdate=func.now(),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_rooms",
        "created_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
    )
    op.alter_column(
        "chat_rooms",
        "updated_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
        onupdate=func.now(),
    )
    op.alter_column(
        "chat_histories",
        "created_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
    )
    op.alter_column(
        "chat_histories",
        "updated_at",
        server_default=func.now(),
        existing_type=sa.TIMESTAMP,
        nullable=False,
        onupdate=func.now(),
    )
    pass
    # ### end Alembic commands ###
