on: [pull_request]

jobs:
  run-api-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.12.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install poetry
        run: |
          pip install uv
          uv sync --frozen --no-install-project --no-dev

      - name: Run API test
        env:
          CORS_ORIGIN: ${{env.CORS_ORIGIN}}
          DB_HOST: ${{env.DB_HOST}}
          DB_NAME: ${{env.DB_NAME}}
          DB_PASSWORD: ${{env.DB_PASSWORD}}
          DB_PORT: ${{env.DB_PORT}}
          DB_USER: ${{env.DB_USER}}
          OPENAI_API_KEY: ${{env.OPENAI_API_KEY}}
        run: |
          uv run pytest